trigger:
- main

pool: 
  name: Windows Agent


variables: 
  - template: variables.yml

stages:
- stage: CreateApplication
  displayName: Create Application
  jobs: 
  - deployment: CreateApplicationACE
    workspace:
      clean: all
    displayName: Create Application in ACE
    environment: $(environmentValue)
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/creatingapplication.yml
