
trigger:
- main

pool: 
  name: PoC IBK

steps:
  - task: CmdLine@2
    displayName: "Creating bar file"
    inputs:
      script: |
        CALL "C:\Program Files\IBM\ACE\12.0.6.0\ace.cmd" ibmint package --input-path $(system.defaultworkingdirectory)\ace-projects  --project simple-demo --output-bar-file $(system.defaultworkingdirectory)\templates\assets\java.bar
        
        echo "BAR file created"

  - task: CmdLine@2
    inputs:
      script: |
        cd templates\assets
      
        jf rt upload "java.bar" example-repo-local --server-id=josselynhd