trigger:
- main

pool: 
  name: PoC IBK

stages:
- stage: CreateApplication
  displayName: Create Application
  jobs: 
  - deployment: CreateApplicationACE
    workspace:
      clean: all
    displayName: Create Application in ACE
    environment: $(environmentValue)
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - task: CmdLine@2
              inputs:
                script: |
                  echo Write your commands here
                  
                  echo Hello world