resources:
  repositories:
    - repository: templates
      endpoint: github-jossHD
      type: github
      name: jossHD/templates
      trigger: none
    - repository: policy-policyname
      endpoint: github-jossHD
      type: github
      name: jossHD/policy-policyname
      trigger: none

trigger:
- main

pool: 
  name: Default

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      cd C:\Users\001664815\Downloads
      
      wget http://ace-bar-gitops-http-my-cp4i.mycluster-dal12-jlhd-ccc03eca20d26e6ac64511f874a64b9b-0000.us-south.containers.appdomain.cloud/simple_api/v1/swagger.json -o miau.json