
trigger:
- main

pool: 
  name: PoC IBK

steps:

- task: CmdLine@2
  inputs:
    script: 'jf rt upload "C:\Users\001664815\IBM\ACET12\workspace\BARfiles\java.bar" example-repo-local --server-id=josselynhd'
