trigger:
- main

pool: 
  name: Windows Agent

parameters:
- name: appOptions
  displayName: Application options
  type: object
  default:
    - name: 'api-apiname'
      secret: []
    - name: 'lib-libname'
      secret: []


variables: 
  - template: variables.yml


stages:
- stage: CreateApplication
  displayName: Create Application
  jobs: 
  - deployment: CreateApplicationACE
    workspace:
      clean: all
    displayName: Create Application in ACE
    environment: $(environmentValue)
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/creatingapplication.yml
