
trigger:
- main

pool: 
  name: PoC IBK

steps:

- task: JfrogCli@1
  inputs:
    artifactoryService: 'jfrog-service'
    command: 'jfrog rt upload "C:\Users\001664815\IBM\ACET12\workspace\BARfiles\java.bar" example-repo-local --server-id=josselynhd'