
trigger:
- main

pool: 
  name: PoC IBK

steps:

- task: CmdLine@2
  inputs:
    script: |
      cd C:\Users\001664815\IBM\ACET12\workspace\BARfiles
      
      jf rt upload "java.bar" example-repo-local --server-id=josselynhd