trigger:
- main

pool: 
  name: PoC IBK

variables: 
  - template: variables.yml

steps:
- task: CmdLine@2
  inputs:
    script: 'echo http://$(is-name)-http-$(namespaceSecret).$(cluster-endpoint)/$(project-name)/v1/swagger.json -o $(project-name).json'