
trigger:
- main

pool: 
  name: PoC IBK

variables: 
  - template: variables.yml

- stage: PublishApplication
  displayName: Publish Application in APIC
  dependsOn: DeployApplication
  jobs: 
  - deployment: PublishAPIC
    workspace:
      clean: all
    displayName: Publishing in APIC
    environment: $(environmentValue)
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/publishing-api.yml

- stage: TestingApplication
  displayName: Testing Application in APIC
  dependsOn: PublishApplication
  jobs: 
  - job: GetCredentials
    steps:
    - bash: |
        echo "##vso[task.setvariable variable=xAPIKey;isOutput=true]$(xapikey)"
        echo "##vso[task.setvariable variable=xAPISecret;isOutput=true]$(xapisecret)"
      name: credentials
  - deployment: ResquestTestingAPI
    dependsOn: GetCredentials
    workspace:
      clean: all
    displayName: APIC Testing
    environment: $(environmentValue)
    timeoutInMinutes: 1
    cancelTimeoutInMinutes: 1
    variables:
      xapikey: $[dependencies.GetCredentials.outputs['credentials.xAPIKey']]
      xapisecret: $[dependencies.GetCredentials.outputs['credentials.xAPISecret']]
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/testing-api.yml