steps:

  - task: CmdLine@2
    displayName: "Clone Git"
    inputs:
      script: |
        git clone https://github.com/jossHD/devops-pipeline.git

  - task: CmdLine@2
    displayName: "Creating bar file"
    inputs:
      script: |
        CALL "C:\Program Files\IBM\ACE\12.0.6.0\ace.cmd" ibmint package --input-path $(system.defaultworkingdirectory)\devops-pipeline\ace-projects  --project simple_api --output-bar-file $(system.defaultworkingdirectory)\devops-pipeline\templates\assets\api.bar
        
        echo "BAR file created"
  - task: CmdLine@2
    displayName: "Creating bar file with tests"
    inputs:
      script: |
        CALL "C:\Program Files\IBM\ACE\12.0.6.0\ace.cmd" ibmint package --input-path $(system.defaultworkingdirectory)\devops-pipeline\ace-projects  --project simple_api_Test --output-bar-file $(system.defaultworkingdirectory)\devops-pipeline\templates\assets\api_Test.bar
        
        echo "BAR file with tests created"

  - task: CmdLine@2
    displayName: "Installing bars into test server"
    inputs:
      script: |
        CALL "C:\Program Files\IBM\ACE\12.0.6.0\ace.cmd" mqsibar --working-directory $(system.defaultworkingdirectory)\devops-pipeline\ace-projects\TEST_SERVER --bar-file $(system.defaultworkingdirectory)\devops-pipeline\templates\assets\api.bar

        CALL "C:\Program Files\IBM\ACE\12.0.6.0\ace.cmd" mqsibar --working-directory $(system.defaultworkingdirectory)\devops-pipeline\ace-projects\TEST_SERVER --bar-file $(system.defaultworkingdirectory)\devops-pipeline\templates\assets\api_Test.bar

  - task: CmdLine@2
    displayName: "Running tests"
    inputs:
      script: |
        CALL "C:\Program Files\IBM\ACE\12.0.6.0\ace.cmd" IntegrationServer --work-dir $(system.defaultworkingdirectory)\devops-pipeline\ace-projects\TEST_SERVER --test-project simple_api_Test --start-msgflows false

  - task: JfrogCli@1
    displayName: "Upload bar in Artifactory"
    inputs:
      artifactoryService: 'jfrog-service'
      command: 'jfrog rt upload "$(system.defaultworkingdirectory)\devops-pipeline\templates\assets\api.bar" example-repo-local'

