steps:
  - checkout: self

  - task: CmdLine@2
    displayName: "Creating bar file"
    inputs:
      script: |
        CALL "$(ace-directory)" ibmint package --input-path $(system.defaultworkingdirectory)\ace-projects  --project $(project-name) --output-bar-file $(system.defaultworkingdirectory)\templates\assets\$(project-name).bar
        
        echo "BAR file created"
  - task: CmdLine@2
    displayName: "Creating bar file with tests"
    inputs:
      script: |
        CALL "$(ace-directory)" ibmint package --input-path $(system.defaultworkingdirectory)\ace-projects  --project $(project-name-test) --output-bar-file $(system.defaultworkingdirectory)\templates\assets\$(project-name-test).bar
        
        echo "BAR file with tests created"

  - task: CmdLine@2
    displayName: "Installing bars into test server"
    inputs:
      script: |
        CALL "$(ace-directory)" mqsibar --working-directory $(system.defaultworkingdirectory)\ace-projects\TEST_SERVER --bar-file $(system.defaultworkingdirectory)\templates\assets\$(project-name).bar

        CALL "$(ace-directory)" mqsibar --working-directory $(system.defaultworkingdirectory)\ace-projects\TEST_SERVER --bar-file $(system.defaultworkingdirectory)\templates\assets\$(project-name-test).bar

  - task: CmdLine@2
    displayName: "Running tests"
    inputs:
      script: |
        CALL "$(ace-directory)" IntegrationServer --work-dir $(system.defaultworkingdirectory)\ace-projects\TEST_SERVER --test-project $(project-name-test) --start-msgflows false

  - task: JfrogCli@1
    displayName: "Upload bar in Artifactory"
    inputs:
      artifactoryService: 'jfrog-service'
      command: 'jfrog rt upload "$(system.defaultworkingdirectory)\templates\assets\$(project-name).bar" $(jfrog-repo)'
  
  - task: CmdLine@2
    displayName: "Creating IS"
    inputs:
      script: |
        oc apply -f integration-server/templates/integration-server.yaml


